# Generated by Django 3.2.6 on 2021-11-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Popular_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='slider_image')),
                ('name', models.CharField(max_length=255)),
                ('context', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='product_cover_image')),
                ('price', models.IntegerField(blank=True, default=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.CharField(max_length=100)),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True)),
                ('designer', models.CharField(max_length=255)),
                ('sale_percant', models.IntegerField(blank=True, default=0, null=True)),
                ('sale_time', models.DateField(blank=True, null=True)),
                ('brand', models.ManyToManyField(blank=True, db_index=True, null=True, related_name='product_brand', to='store.Brand')),
                ('colors', models.ManyToManyField(blank=True, db_index=True, null=True, related_name='product_color', to='store.Color')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(related_name='shopping_card_of_user', to='store.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCardOfUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping Card Of User',
                'verbose_name_plural': 'Shopping Cards Of User',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('rate', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('message', models.TextField(max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.review')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('size', 'Size'), ('color', 'Color'), ('brand', 'Brand')], max_length=20)),
                ('value', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('brown', 'Brown'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('gold', 'Gold'), ('purple', 'Purple'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='store.productversion')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_detail_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/category_images/')),
                ('description', models.TextField(max_length=2000)),
                ('category', models.ManyToManyField(db_index=True, to='store.Category')),
                ('tags', models.ManyToManyField(db_index=True, to='store.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL)),
                ('user_of_shopping_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_card_item', to='store.shopping_card')),
            ],
            options={
                'verbose_name': 'Basket Item',
                'verbose_name_plural': 'Basket Items',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(related_name='basket_of_user', to='store.BasketItem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basketOfUser', to=settings.AUTH_USER_MODEL)),
                ('zip_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket_of_zip', to='about.zipcode')),
            ],
            options={
                'verbose_name': 'Basket Of User',
                'verbose_name_plural': 'Baskets Of User',
            },
        ),
    ]
