# Generated by Django 3.2.6 on 2021-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_basketitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_card',
            name='product',
        ),
        migrations.AddField(
            model_name='shopping_card',
            name='items',
            field=models.ManyToManyField(related_name='shopping_card_of_user', to='store.BasketItem'),
        ),
    ]
