# Generated by Django 3.2.6 on 2021-11-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211115_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_card',
            name='items',
        ),
        migrations.AddField(
            model_name='shopping_card',
            name='product',
            field=models.ManyToManyField(related_name='shoppingCardOfProduct', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
