# Generated by Django 3.2.6 on 2021-11-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211116_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_card',
            name='item',
            field=models.ManyToManyField(related_name='shoppingCardOfItem', to='store.BasketItem'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
