# Generated by Django 3.2.6 on 2021-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211118_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='user_of_shopping_card',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
