# Generated by Django 3.2.6 on 2021-11-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='user_of_shopping_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_card_item', to='store.shopping_card'),
        ),
    ]
