version: '3.1'

services: 

  db:
      image: postgres
      restart: always
      ports: 
        - "5432:5432"
      volumes: 
        - ./pgdb:/var/lib/postgresql/data
      env_file: ./.envv
      
  redis:
    image: redis
    restart: always
    ports: 
      -  6379:6379
  
  # celery:
  #   build: 
  #     context: .
  #     dockerfile: celery.dockerfile
  #   restart: always
  #   command: celery -A Pavshop worker --beat --scheduler django --loglevel=info
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - "db"
  #     - "redis"
  #   env_file: ./.envv

