# Generated by Django 3.2.6 on 2021-11-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_data',
            name='data',
        ),
    ]
